spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
          filters:
            - name: CircuitBreaker
              args:
                name: projectServiceCircuitBreaker
                fallbackUri: forward:/projectServiceFallback
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**

resilience4j:
  timelimiter:
    instances:
      projectServiceCircuitBreaker:
        timeoutDuration: 2s
  circuitbreaker:
    instances:
      projectServiceCircuitBreaker:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        automatic-transition-from-open-to-half-open-enabled: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always