spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
  redis:
    connect-timeout: 30s
    host: localhost
    port: 6379
    timeout: 1s
